all check clean:
	$(MAKE) -C 01-hello_world x$@
	$(MAKE) -C 02-hello_cargo x$@
	$(MAKE) -C 03-guessing_game x$@
	$(MAKE) -C 04-slice x$@
	$(MAKE) -C 05-formatting x$@
	$(MAKE) -C 06-impl_demo x$@
	$(MAKE) -C 07-clap x$@
	$(MAKE) -C 08-enum_demo x$@
	$(MAKE) -C 09-log_demo x$@
	$(MAKE) -C 10-modules_demo x$@

include ./common.mk
